language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - $HOME/gopath/bin/goveralls -race -service=travis-ci
  - make build
